language: node_js
node_js:
  - '12'
jobs:
  include:
    - stage: pre-test
      script:
        - yarn audit
        - yarn lint
    - stage: test
      script: yarn test
    - stage: build
      script: yarn electron-pack
