language: node_js
node_js:
  - '12'
jobs:
  include:
    - stage: test
      script: yarn ci
    - stage: build
      os: osx
      if: tag IS present AND branch = master
      script: yarn electron-pack
